### ISSUE TITLE
Can no longer see all buttons at all times

### ISSUE THREAD

**Issue by Amerigowarlock** [seblindfors/ConsolePort#101]
Hello, since last patch, despite the option being enabled, i can no longer see all the buttons on the clusters.
Neither at all times, nor when mouseover, not even on CD.

This is an option i can hardly play with :/

Hopefully you see this and fix it quick ! 

Thanks a lot for this great addon that i absolutly love !!

**Comment by OrochiX1992** [comment]
im having the same issue. just did the update and im wanting to get the older version now just so i can see whats going on. this update and major change to everything wasnt needed and looks to have removed all my profiles i had setup.
