### ISSUE TITLE
New Esc Menu Issue/Request

### ISSUE THREAD

**Issue by Lenisa98** [seblindfors/ConsolePort#105]
Hello. One of the new ConsolePort updates seems to have changed the Esc menu to one that looks pretty much like the default one (seen on the attached photo). The issue is that this new menu doesn't seem to register inputs from the controller without having the ConsolePort settings -> Interface -> Interface Cursor enabled. The old Esc menu (the one that looked a lot more like the menu in FFXIV) worked just fine without the Interface Cursor enabled. 
On the new menu, when pressing R1 to go to the new Radial Menu with all the things like inventory, character stats and so on, the inputs work just fine. It's only at the initial Esc menu box seen on the photo where inputs don't register. 

Would it be possible to make the input work without the Interface Cursor enabled like the old menu? Or alternatively, would it be possible to add a setting somewhere where users can switch between this new Esc Menu layout and the old FFXIV style one? 
Thank you in advance!

![image_2024-06-29_102106194](https://github.com/seblindfors/ConsolePort/assets/36400245/c1601e35-57b1-4e9a-8eb9-447bf7e9eaf8)

And thank you for making this addon btw, it is number 1 essential to make this game comfortable to play for me. Cannot express how much I appreciate having it!

**Comment by seblindfors** [comment]
No. The change in this case comes from TWW having anonymous game menu buttons, so they cannot be proxied like they were in the previous game menu. Essentially to have a menu that works in combat, you'd need those proxies, so it's interface cursor or mouse clicks if you want to click on the default game menu buttons.

And I have never looked at FFXIV for inspiration. :P
