### ISSUE TITLE
Raid Cursor is not working as intended in Follower dungeons.

### ISSUE THREAD

**Issue by Xinkle** [seblindfors/ConsolePort#109]
When targeting a Follower with the Raid Cursor and using an attack skill, the Raid Cursor should be able to attack enemies normally, even if it is targeting a party member.
However, in the Follower dungeon, this is not the case and the output says it is an invalid target.

**Comment by seblindfors** [comment]
Correct me if I'm wrong, but I think this was fixed by https://github.com/seblindfors/ConsolePort/commit/1d3b8749c3a821326f754c46a2f61a389d1af772

**Comment by Xinkle** [comment]
I'll check it today

**Comment by Xinkle** [comment]
sorry for late it fixed! Thanks!
