### ISSUE TITLE
Mouse "semi stuck" on character selection screen.

### ISSUE THREAD

**Issue by PieceOfPanic** [seblindfors/ConsolePort#111]
I sometimes get a bug where my mouse is "semi stuck" on the character selection screen, after I log out. The mouse will get stuck in the "areas" where the cursor moves in the bag or in the character stat UI etc., as if I was still in using controller inside the game.
-I can move the mouse out of the area though, with bruteforce keep moving the mouse, but it still acts the same. Just in a new area.

**Comment by seblindfors** [comment]
Not a bug with the addon, report to Blizzard. But, as a pro tip, nudge your camera/mouse control stick and it will probably stop.
