### ISSUE TITLE
Feature Request: LT and LB Bindings

### ISSUE THREAD

**Issue by adreaver** [seblindfors/ConsolePort#12]
Requesting the ability to independently bind LT and LB. This should then "grey out" the option to keybind the affected button combinations; e.g. if you bind LT to Shift, you can no longer bind LT+Y or LB+LT+A, but your LB+X binding would be unaffected.

The intention is to offer an option allowing the keybinds to better fit with a modifier-macro-based keybinding configuration.

**Comment by seblindfors** [comment]
This already exists. All you have to do is clear the combination of the button that you would like to use for modifier macros. 

E.g. if you want to use B as your base binding, then just clear LT+B by right clicking on it in the binding config. This will make that binding default to the base binding and allow you to use modifier macros.
