### ISSUE TITLE
Invisible cursor

### ISSUE THREAD

**Issue by RRinscheid** [seblindfors/ConsolePort#122]
Hey all, I play on Steam Deck I'm getting the dreaded invisible cursor problem and I know I'm not the only one that has had this happened to. 

This had happened to me in the past but was solved after I rolled back to a previous steam OS. However the evil glitch came back again and now I'm stumped as how to fix this. Any suggestions?

**Comment by zjy901231** [comment]
I'm facing the same issue, is there any solutions?

**Comment by seblindfors** [comment]
Added a fix for this, but this will only apply for new users.
You can fix it by changing `Settings > Cursor > Use Hardware Mouse Cursor`
https://github.com/seblindfors/ConsolePort/commit/3abdd5ec8bda4f86c03044d61e7cd715673c0b2b
