### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Praefectvs** [seblindfors/ConsolePort#13]
Hello, 
I have d/l and tried your consoleport, however, I am used to inverting y axis.
Is there any chance you will be adding that as an option in the future?

**Comment by seblindfors** [comment]
![7637afc66b4cd60f6df4c97854f5912e](https://cloud.githubusercontent.com/assets/7464938/13474967/a2968cd4-e0c0-11e5-880d-f3f229bea933.png)

**Comment by Praefectvs** [comment]
Hello,
I think I didn't explain properly.
I mapped the movement to the left stick on the controller, and do not want
to use the mouse for the "look", but rather the right stick. I want the
controller to function the same as console games.
For some reason it would not work, and I assumed it was the inversion.
I will have to try again, when I get home, so I can give you the exact
issue.
