### ISSUE TITLE
Boss Button

### ISSUE THREAD

**Issue by Irwine** [seblindfors/ConsolePort#14]
Hello,
First of all thanks for your mod I love it, thanks to it I can come back and play to WoW.
I have just notice a little problem when I am in raid on Iskar I can't use the boss button, i have soluce this little problem with a macro and have a focus player.
Have you already correct this issue?
Please excuse me for my english, but I am french.
Thank you for your work and continue on it.

**Comment by seblindfors** [comment]
Binding explicitly to the extra action button should work in that encounter. If you're meaning the raid cursor, then that will probably not work since it doesn't know how to behave in situations with a temporary spell like that.
