### ISSUE TITLE
Unmount vehicle

### ISSUE THREAD

**Issue by Irwine** [seblindfors/ConsolePort#15]
Hello, 
I have a problem went i unmount from a vehicle (canon on the iron harbor in the tanaan jungle), I must deconnect and reconnect from the game because I can use any sort or other shortcut from ma bars.
Have you any idea of the cause of this bug?
I use a interface addon elvui.
Tanks again for your work and your time

**Comment by seblindfors** [comment]
If this happens with ElvUI disabled then that's a problem that needs investigating. However, ElvUI modifies some of the action bar behavior on the standard bars from Blizzard, which causes issues since ConsolePort is using the regular bars behind the scenes.
