### ISSUE TITLE
ConsolePortKeyboard: backspace erases half of multi-byte character

### ISSUE THREAD

**Issue by ghost** [seblindfors/ConsolePort#18]
When backspacing russian characters I have noticed that first it becomes a question mark, then it gets deleted, which means that top byte gets erased first, then lower. Can you please add some option(or detect it somehow) for non-ASCII languages to have multibyte characters properly deleted?
![multibyte_bs](https://cloud.githubusercontent.com/assets/814651/14760768/bdc0161a-094c-11e6-8fd1-fa62769a19ed.jpg)

**Comment by seblindfors** [comment]
There are actually equivalent cursor functions for multibyte characters, but I never used it since it wasn't relevant to English. I'll look into it and if it's a minor fix it'll be added in the next patch.
