### ISSUE TITLE
Keyboard: jump instead of space in chat when using PC keyboard

### ISSUE THREAD

**Issue by Baldrs** [seblindfors/ConsolePort#20]
I have tried to just type commands in from my laptops keyboard(because layout switch is deep in settings and cannot be accessed with keyboard being opened), and I have noticed that if I press space on the keyboard with chat window open, character instead jumps and chat window gets closed. Instead I need to use `Y` from controller, which in that case inserts both space and 6(I have it bound to 6 on my controller)

**Comment by Baldrs** [comment]
This only relevant because player cannot switch layouts as I posted in #19

**Comment by Baldrs** [comment]
Also I have tried to swap buttons(close with space) to avoid different meanings(physical space closes the keyboard)

So with changes it looks like that: 
![swap space-close](https://cloud.githubusercontent.com/assets/814651/15274586/01d936c2-1ab6-11e6-9f02-1288a410983e.png)

For me that feels logical change, as `A` on the controller is mapped to space(jump) anyway, so at least for me it feels natural to expect that it will be space in keyboard as well. I can create a pull request for this, but it feels unright to do so without any prior approval.

**Comment by seblindfors** [comment]
Physical space does not close the keyboard on an English client. I'm not sure why it does on a Russian client. Usually, when you press a button that isn't bound to the controller itself, the keyboard will fade out and let you type as usual. It refreshes the time out anytime you press a button that doesn't belong to the controller, which should let you use the physical space button along with any other button that's not bound to ConsolePort.

**Comment by seblindfors** [comment]
The keyboard addon does need some work, not only in this area, but I haven't got around to it yet.

**Comment by Baldrs** [comment]
Well then I just need to rebind it to something else and recalibrate.
