### ISSUE TITLE
Lowest wow version required

### ISSUE THREAD

**Issue by solidstudio** [seblindfors/ConsolePort#21]
Hi tried to add the addon to version 1.12.1 but it didn't work. What version is required? Is there a version that will work with 1.12.1? Thanks

**Comment by seblindfors** [comment]
Nope, and there won't be. First and foremost, private servers are in violation of Blizzard's terms of use. If that ever changes, I'll allow someone else to port it if they really want to. Also, the systems used in vanilla to manage bindings and secure actions is vastly different from BC and onward. It would entail a complete rewrite to make it work on vanilla servers.
