### ISSUE TITLE
Stuck going forwards

### ISSUE THREAD

**Issue by BanditBanditBandit** [seblindfors/ConsolePort#25]
I have been using this addon successfully for a few days, but I have run into this issue a few times. I barely tap back on the L stick and it starts to run forwards and won't stop, sometimes slightly tapping forward on the stick will also get it stuck running forwards. I have changed the dead zone and it does not help, what have I done wrong? it feels like all that happened was you guys updated the addon, or wowmapper had an update both in a short time. how should I test this to figure out what to fix?

**Comment by BanditBanditBandit** [comment]
Found what the issue was, it was the setting to toggle auto run/walk. Because I have modified my autorun to the / and changed walk to Shift /

For some reason it was working before fine, why is it not reading my keybindings?

**Comment by seblindfors** [comment]
Disable the feature if you're having issues. Regardless, it's not an issue with ConsolePort because ConsolePort can't control movement.
