### ISSUE TITLE
Raid Cursor and Elvui

### ISSUE THREAD

**Issue by reapa1234** [seblindfors/ConsolePort#27]
Im not sure if its raid cursor or elvui but when I am using elvui raid cursor either throws up a error message or does absolutly nothing but as soon as I disable elvui raid cursor works fine. Any chance you can look into getting raid cursor to work with elvui if its not too much of a big task :) Thanks.

**Comment by seblindfors** [comment]
I recommend getting Grid as raid frames and disabling whatever ElvUI offers. The problem is unfixable from ConsolePort's point of view.
