### ISSUE TITLE
Targeting not working after upgrade

### ISSUE THREAD

**Issue by crohde7707** [seblindfors/ConsolePort#29]
@seblindfors I upgraded from 1.3.1 to 1.3.3 when the new patch launched yesterday. After this upgrade, the targeting doesn't seem to be working. I am using a DS4 controller, and the targeting is auto bound to L1+R1. It doesn't seem to be doing anything, even when i click on the button directly in mouse mode, it doesn't target anything any longer

**Comment by crohde7707** [comment]
Managed to fix it by rebinding to target nearest enemy. That will work for me

**Comment by seblindfors** [comment]
Target Scan Enemy (Hold) is the default targeting binding as of 7.0, but Blizzard managed to break it in the 7.1 patch update. This is an official game binding and not provided specifically by ConsolePort.
They will either fix it or remove it, but either way I have no control over it.
