### ISSUE TITLE
Blank settitng pages

### ISSUE THREAD

**Issue by SonicGummo** [seblindfors/ConsolePort#31]
Hello. 
I like to submit problem with your Great Addon.
It happened after last update, before was OK.
When i open CONTROLS / SETTINGS, i see only boxes with titles (Gneral settings, Interact button, Loot button), but the rest of boxes is empty. 

Just after login, in BugSack is only one BUG report:

1x ConsolePort\Config\Controls.lua:240: bad argument #2 to 'SetFormattedText' (string expected, got nil)
[C]: in function `SetFormattedText'
ConsolePort\Config\Controls.lua:240: in function `OnShow'
ConsolePort\Config\Controls.lua:527: in function `onLoad'
ConsolePort\Frames\Config.lua:415: in function `AddPanel'
ConsolePort\Frames\Config.lua:564: in function `CreateConfigPanel'
ConsolePort\Core\Events.lua:185: in function `?'
ConsolePort\Core\Events.lua:218: in function <ConsolePort\Core\Events.lua:216>

Locals:
(*temporary) = ConsolePortConfigContainerControlsBindWrapperBindCatcher {
 0 = <userdata>
 HighlightTexture = <unnamed> {
 }
 Label = <unnamed> {
 }
 OnHide = <function> defined @ConsolePort\Config\Controls.lua:232
 OnShow = <function> defined @ConsolePort\Config\Controls.lua:237
 SelectedTexture = <unnamed> {
 }
 CurrentButton = "CP_R_GRIP"
 Cover = <unnamed> {
 }
 OnClick = <function> defined @ConsolePort\Config\Controls.lua:224
 Catch = <function> defined @ConsolePort\Config\Controls.lua:207
 Icon = <unnamed> {
 }
 cvar = "interactWith"
}
(*temporary) = "|T%s:50:50:0:0|t"
(*temporary) = nil
(*temporary) = "string expected, got nil"

Thank You.
Petr.

**Comment by seblindfors** [comment]
This is a compatibility issue coming from pre 1.4.1 where you were using the right grip button as the interact button. The ID of that button has been changed, causing the loading process to go bonkers and cancel itself midway through. No fix will be added for this issue, but you can fix it yourself by importing this data in the advanced tab:
```b4vmErLxtDuzUvMCHXMFGnxz0rxAUD2CErLxtLMB0vMCHngDxLgDO51udb1xurJx05fDE5f```
After importing this data string, click `Apply changes` and then `Merge`. This should solve your problem.

**Comment by SonicGummo** [comment]
Hi. 

 

I can now see the options. 

Wanted to help with maybe bug that can help more people.

 

Thank You for fast reaction.

 

Petr.

**Comment by SonicGummo** [comment]
Sorry to bother you again, is there any way to change controller back to STEAM controller ?

I see Playstation controller now, and cant return it back, even after delete WTF settings.

Also i cant speak with any quest giver and so…
