### ISSUE TITLE
Add a close button in the Export's dialogue top right corner

### ISSUE THREAD

**Issue by boskee** [seblindfors/ConsolePort#47]
I've just launched WoW on my Steam Deck with ConsolePort installed. After misclicking [X] in the initial key bindings dialogue, it opened the export button next to it (i'd move that elsewhere too as it's really easy to misclick on a touchscreen device). Now I'm stuck inside the Export dialogue with no way to close it. I suspect there may be a close button below the text field used to copy the import string, but I wouldn't know - it shows off the screen. Quick solution would be to add an [X] button in the top right corner of the Export dialogue.

**Comment by seblindfors** [comment]
Addressed this by adding some checks to see if the config frames fit.
d0aaa3f119257e440656c8f5bd8bb056a70f719b
