### ISSUE TITLE
TBC Instant Crash when using 2.4.0

### ISSUE THREAD

**Issue by dciborow** [seblindfors/ConsolePort#48]
Enabling 2.4.0 of Addon with TBC Classic (2.5.4.44833) results in crash due to unexpected error.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/9027725/181996075-81c511f4-bcfc-4106-ab7a-c6d2094a91de.png">

**Comment by seblindfors** [comment]
Game bug due to a device that fails to identify itself, usually devices that are combined keyboard/gamepad in one cable. Not a CP issue.
