### ISSUE TITLE
2.4.2 Crash On Login

### ISSUE THREAD

**Issue by Astyn** [seblindfors/ConsolePort#49]
![image](https://user-images.githubusercontent.com/3835856/187994568-07a41125-f166-48cc-9219-badef9303139.png)

Hi there,

When I enable console port with no other addons enabled, it causes the game (Wotlk Classic PrePatch) to crash. I can be logged in fine, but as soon as i exit the menu after enabling, the game crashes. I saw another issue was raised like this recently, but that mentioned peripherals? I have nothing other than a keyboard and trackpad (on laptop); I was going to get the game pad sorted once i get the addon running.

Cheers,
Astyn

UPDATE: Seems this also happens when I try /Console GamePadEnable 1, any ideas?

**Comment by seblindfors** [comment]
This can happen as a result of using hybrid gamepad/keyboard devices, such as the Razer Tartarus. It's not an addon issue, more so with how the game handles your devices it thinks are gamepads.
