### ISSUE TITLE
Steam Deck use

### ISSUE THREAD

**Issue by hellj85** [seblindfors/ConsolePort#51]
Wondering if this is a known issue using console Port with WoW on a steam deck...
When using the trackpads to move the cursor, the majority of buttons and menu selections become no longer functional. 
I can push any number of buttons and can see the blue indicator noting that that button is being pushed, but the skill or action bound to that location does not execute. The exception being jump. Macros, skills, actions will not function. Accessing the interface menu, one cannot open/access any menu, log out or exit game, the exception here is the controls menu may be accessed and functions normally.
This is remedied by doing a /reload ui in the chat window, but the problem simply recurs following trackpads usage.
The semi-solution is do not use trackpads, but that is not a viable long term solution.
Thoughts?

**Comment by seblindfors** [comment]
This is probably not an addon issue, more so by moving the touchpad, you're putting the controller part of the Deck into a desktop type mode, and your inputs are therefore disabled. There is no issue with the addon if you want to do something with your regular mouse and keyboard.
