### ISSUE TITLE
(Version 2.5.5+) Jump Button Now Barely Works and Instead just Toggles Cursor and Crosshair [PS4 Controller]

### ISSUE THREAD

**Issue by hekemp** [seblindfors/ConsolePort#53]
Hello hello - I'm new to WoW, so please bare with me on any terminology I may get wrong :) 

I've been using ConsolePort with a PlayStation 4 controller on version 2.5.4. I decided to update things today, and when I updated to 2.5.7, all of a sudden my jump button stopped working. Instead, it seemed to toggle the cross hairs in the middle of the screen with the cursor in game. Occasionally, once in a blue moon, the jump _did_ work (seemingly because I was locked on to something?), but 99% of the time, just the cursor in the center of the screen toggled. Reverting to 2.5.6 and 2.5.5. did not fix the issue, only 2.5.4 reverted this issue, so I think something in 2.5.5 might have messed up the Jump button binding and/or cursor toggle, at least on PS4.

**Comment by seblindfors** [comment]
I think your issue was probably resolved by restarting the game, or some other external circumstance. Nothing in particular has been changed about jumping or mouse handling during those patches.
