### ISSUE TITLE
Interface Cursor > Repeated Movement broken

### ISSUE THREAD

**Issue by DGmip** [seblindfors/ConsolePort#54]
Repeated movement no longer seems to work, was a really nice feature that allowed me to move the cursor quickly through my bags and it being broken makes a lot of work I do with the controller tedious.

To replicate, open your bags with mouse cursor enabled and hold down a direction.

Using xbox controller.

**Comment by seblindfors** [comment]
https://github.com/seblindfors/ConsolePort/commit/e1dde3a58bbb81ddb541e03e33b75e5ce3248437
