### ISSUE TITLE
Mod is incompatible with Steam Link

### ISSUE THREAD

**Issue by rcmaehl** [seblindfors/ConsolePort#61]
**Steps to reproduce:**

- Connect XBox controller  to a device running Steam Link
- Verify Steam Link detects the controller as XBox
- Connect to Steam
- Launch WoW

**Expected Results:**

Xbox controller properly works

**Actual results:**

Mappings are broken.

**Workaround:**

Connect controller via bluetooth to device being controlled by steam link, if possible

**Comment by seblindfors** [comment]
Such issues have to do with whether the game can see your controller. Not an addon issue.
