### ISSUE TITLE
Steam deck ConsolePort Can’t use my left stick to move forward. 

### ISSUE THREAD

**Issue by darkraven92** [seblindfors/ConsolePort#63]
I been playing wow on my steam deck using ConsolePort and it have been working out great for a long time. But one day I wanted to connect my SD to the TV to play using a Xbox one wireless controller and after I had connected it, an problem appeared where I could no longer use my left stick Y-axis anymore to move my character forward. I have tried to completely remove my Xbox controller and play on my SD. I have also tried to reset every setting in ConsolePort but with no success. I have also completely uninstalled ConsolePort and then reinstalled it but also with no success. Now in a last attempt I am going to reinstall wow and see if that will help. 
Have anyone experienced something similar or have anyone any ideas on how to fix this? Thanks in advance!

**Comment by seblindfors** [comment]
You probably changed your controller mapping to something that doesn't work.
![image](https://github.com/seblindfors/ConsolePort/assets/7464938/fa57a4df-dd3e-47ed-b1ac-cb66db14a150)
