### ISSUE TITLE
Main action bar actions not working

### ISSUE THREAD

**Issue by kilabyte** [seblindfors/ConsolePort#7]
i got everything up and working as per the readme however none of my square triangle etc action buttons work. So i can see in the action bar the item highlighting when i press the button but the action is never executed.

If my i move my actions to the bar above the main action bar everything works fine. Any ideas?
![screen shot 2015-08-29 at 2 38 00 pm](https://cloud.githubusercontent.com/assets/487948/9564419/9118d41e-4e5b-11e5-82a3-945cec6d9901.png)

**Comment by seblindfors** [comment]
What addons are you using alongside ConsolePort? There might be a conflict there.

Here are a couple commands that you can run and what they should return with a fresh install:

Checking action page:
* /dump CP_R_UP_NOMOD:GetAttribute("actionpage")
* should return [1]="1"

Checking action:
* /dump CP_R_UP_NOMOD:GetAttribute("action")
* should return [1]=2

Checking action name:
* /dump CP_R_UP_NOMOD.action:GetName()
* should return [1]="ActionButton2"

**Comment by kilabyte** [comment]
I just have Carbonite Quest installed.
![screen shot 2015-08-29 at 2 51 11 pm](https://cloud.githubusercontent.com/assets/487948/9564468/702bd9ca-4e5d-11e5-8ee6-f2d1de2effa8.png)

**Comment by seblindfors** [comment]
This might seem like a weird question, but what spec are you playing?

**Comment by kilabyte** [comment]
Human Paladin

**Comment by seblindfors** [comment]
Try calling this function:
* /run ChangeActionBarPage(1)

Also, have you checked if the issue happens on other characters?

**Comment by kilabyte** [comment]
yes! now it works perfectly! Is this a bug? Will i have to do it every time i run my game?

**Comment by seblindfors** [comment]
Unless they made changes to action bar paging in the last WoW patch, it was most likely a bug on Blizzard's end. I've never run into this issue before with extensive testing on every class in the game. Usually when you have a so called "tempshapeshift" action bar, it has its own page number and the addon takes that into account when changing pages on the "fake" buttons. 

Anyway, is the bug still there if you logout and back in again?

**Comment by seblindfors** [comment]
After some investigation, it seems the bug happens when the main bar has a tempshapeshift action bar or if you scroll to the second page on the main bar.

**Comment by kilabyte** [comment]
ya when i quit and re open the game the issue comes back. Also would you be able to make the add on work with the other add on Storyline?

**Comment by seblindfors** [comment]
I'm going to add support for addons soon, but for now, you can use this macro to add Storyline:
/run ConsolePort.AddFrame(Storyline_NPCFrame, ConsolePort.UIControl, "UIControl"); Storyline_NPCFrameChatNext.hasPriority = true

**Comment by seblindfors** [comment]
I located the bug in my code. I will have it fixed in the next update. A simple fix is probably just changing to action page 2 and then back again.

**Comment by kilabyte** [comment]
thats awesome thank you so much! now that the addon works with Storyline its even better! and yes a quick fix was just to toggle the action bar. I'm glad i could help :) :+1:

**Comment by seblindfors** [comment]
The most recent update on GitHub has the fix you're looking for. It also has a taint issue, causing actions to be blocked after changing button bindings in interface options. A simple way around it is to just /reload, but I won't upload to curse/wowinterface until I've fixed the problem. 

Since your issue was resolved, I'm closing this topic now. Again, thanks for the feedback!
