### ISSUE TITLE
WoW Classic Installed with +Hardcore Add-on Breaks ConsolePort

### ISSUE THREAD

**Issue by ReportingBygz** [seblindfors/ConsolePort#77]
controle movement becomes inverted

**Comment by seblindfors** [comment]
I don't think the two are related in the slightest. You're likely just having an issue with your controller mappings. You can try to reset your configuration by using the chat command `/cp resetconfigs`, or follow the directions outlined here:
https://discord.com/channels/187704823657922560/1021493574874968094
