### ISSUE TITLE
No movement but all other buttons work with ConsolePort in classic

### ISSUE THREAD

**Issue by sobnock** [seblindfors/ConsolePort#79]
I did reinstall windows , I did reinstall warcraft classic i can not move but all the other buttons work. I did try wow mapper makes wasd work but not the mouse inputs, i did try ps4windows with wowmapper only thing that kind of works but the mouse inputs are insanely fast. rewasd was working but stopped working now. can someone plz update wowmapper as ConsolePort does not let any kind of movement work with just wow. wowmapper just needs to be updated for mouse movement to work.

how do i get ConsolePort to work? it did work about a week ago with just wow , i also did try jocys x360,ps4windows,rewasd.wowmapper , just wow with ConsolePort

**Comment by seblindfors** [comment]
I don't know what you're trying to do, but WoWmapper should not be used with any official version of the game, neither should DS4Windows or other mappers that map gamepad to keyboard/mouse. WoW has native gamepad support.
