### ISSUE TITLE
6th September Retail version; cursor issues

### ISSUE THREAD

**Issue by Lifebringr** [seblindfors/ConsolePort#83]
The cursor is going crazy since the overnight update; tried updating to latest console port version without luck; basically, whenever I open the character or inventory pages and try to use the arrows to navigate, a single arrow press gets stuck(it’s like it doesn’t depress) and pressing the other side makes it go into infinite loop (for example down, then up, it just goes down and up nonstop)

**Comment by mardok79** [comment]
hello, another problem encountered is that the raid cursor no longer goes to the party or raid frame
