### ISSUE TITLE
Add A Way To Set "Target Scan Enemy" To Always On

### ISSUE THREAD

**Issue by MiltyTheGreat** [seblindfors/ConsolePort#93]
Target Scan Enemy is GREAT, but I would love a way to toggle it on, instead of having to hold the button. Now, there may already be a way to do this that I have yet to discover, but if not, I would love a way to toggle this feature. To me, it feels SO much better than the slightly delayed targeting with the crosshair.

**Comment by seblindfors** [comment]
Soft enemy targeting does exactly this. You can turn that on in settings.
