### ISSUE TITLE
PS5 Controller - mic Button not detected. 

### ISSUE THREAD

**Issue by harley-codes** [seblindfors/ConsolePort#98]
Console Port cannot map to the mic button, despite the UI showing it as a feature.
I have tested the button is picked up by my OS(Linux), by using Steams device input test.
If anyone can use this button no issues, please mention, as this may be unique to my machine/setup.

**Comment by seblindfors** [comment]
WoW doesn't recognize the mic button unless your controller is connected by USB. https://github.com/Stanzilla/WoWUIBugs/issues/482
